--- #YAML:1.0
name: Apache2::WebApp::Plugin::Session::MySQL
abstract: Store session data in a MySQL database.
version: 0.02
author:
  - Marc S. Brooks <mbrooks@cpan.org>
license: perl and artistic
distribution_type: module
requires:
  Apache::Session::MySQL: 1.01
  Apache::Session::Lock::MySQL: 1.01
  Apache2::WebApp: 0.01
  Apache2::WebApp::Plugin::Cookie: 0.01
  Apache2::WebApp::Plugin::DBI: 0.01
  Apache2::WebApp::Plugin::Session: 0.01
  Params::Validate: 0
build_requires:
  Apache::Test: 0
resources:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
